"""[mcp-email] Compose a campaign email from a brief's draft — small pure helpers.

No I/O here: give it the brief/draft data and it returns a subject, an HTML body,
and RFC-822 ``.eml`` bytes. Kept side-effect-free so it's trivial to test.
"""
from __future__ import annotations

from email.message import EmailMessage
from html import escape

# Matches the CraftAI documentation palette (accent / ink).
_ACCENT = "#1F6F8B"
_INK = "#1A2530"


def subject_line(brand: str, channel: str, body: str) -> str:
    """Prefer the draft's first non-empty line as the headline; fall back to a generic one."""
    for line in (body or "").splitlines():
        line = line.strip().lstrip("#").strip()
        if line:
            return f"{brand}: {line[:70]}"
    return f"{brand} — {channel.title()} campaign"


def _paragraphs(body: str) -> str:
    """Turn plain draft text into simple HTML paragraphs (blank line = new paragraph)."""
    blocks = [b.strip() for b in (body or "").split("\n\n") if b.strip()]
    return "".join(
        f'<p style="margin:0 0 14px;line-height:1.6;color:{_INK};">'
        f'{escape(block).replace(chr(10), "<br>")}</p>'
        for block in blocks
    )


def _image_block(image_url: str | None) -> str:
    if not image_url:
        return ""
    return (
        f'<img src="{escape(image_url)}" alt="Campaign visual" '
        f'style="width:100%;max-width:560px;border-radius:8px;margin:0 0 20px;">'
    )


def _cta_block(cta: str | None) -> str:
    if not cta:
        return ""
    return (
        f'<div style="margin:22px 0 4px;">'
        f'<span style="display:inline-block;background:{_ACCENT};color:#fff;text-decoration:none;'
        f'padding:11px 22px;border-radius:6px;font-weight:600;font-size:14px;">{escape(cta)}</span>'
        f'</div>'
    )


def render_html(brand: str, channel: str, body: str, image_url: str | None,
                cta: str | None = None) -> str:
    """Assemble the branded HTML email body."""
    return (
        f'<div style="max-width:600px;margin:0 auto;font-family:-apple-system,Segoe UI,Roboto,sans-serif;">'
        f'<div style="background:{_ACCENT};color:#fff;padding:18px 24px;border-radius:8px 8px 0 0;">'
        f'<div style="font-size:20px;font-weight:700;">{escape(brand)}</div>'
        f'<div style="font-size:12px;opacity:.85;text-transform:uppercase;letter-spacing:.5px;">'
        f'{escape(channel)} campaign</div></div>'
        f'<div style="padding:24px;border:1px solid #e5e9ec;border-top:none;border-radius:0 0 8px 8px;">'
        f'{_image_block(image_url)}{_paragraphs(body)}{_cta_block(cta)}'
        f'<hr style="border:none;border-top:1px solid #eef1f3;margin:20px 0;">'
        f'<div style="font-size:11px;color:#8a97a0;">Generated by CraftAI · Intelligent Marketing '
        f'Content Supply Chain</div></div></div>'
    )


def build_eml(subject: str, sender: str, to: str, html: str) -> bytes:
    """Package subject + HTML into RFC-822 ``.eml`` bytes (openable in any mail client)."""
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to
    msg.set_content("This is an HTML campaign email. Open it in an HTML-capable mail client.")
    msg.add_alternative(html, subtype="html")
    return msg.as_bytes()
